# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c1d96a00b70c3078053b1d8f67240196451aa2a867c5067e169ae830a1dd936787b8616bdbe2cfa94b63ed2cc6a4fab0f3ba9d2074d51182697d61c3c5805e8

test:
  secret_key_base: 4cb0c04a2004cadd9028ca5902b770e75793252f166c31574124f525d194ae03c834a6ec7145c3084cbce9cfa51cb53b511f334064303290539a1cf05bcc6bf6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
